#!/bin/bash

repo=fractals
count="0 1 2 3 4 5 6"


# create the fractals
for type in cayley sierpinski ; do
    for i in $count ; do
        echo "# $type $i"
        ./git-$type --repository $repo $i
    done
done

