#!/bin/bash

repo=fractals
count="0 1 2 3 4 5 6"


# create the fractals
for type in cayley sierpinski ; do
    for i in $count ; do
        sleep 1
        ./git-$type --repository $repo $i
    done
done

# push them
cd $repo
git remote add origin git.bruhat.net:git/r/fractals.git
for type in cayley sierpinski ; do
    for i in $count ; do
         git push --force origin $type-$i:$type-$i
    done
done

