#!/usr/bin/env perl
use strict;
use warnings;
use File::Path;
use Getopt::Long;
use GitGraph;

my %conf = ( repository => 'cayley' );
GetOptions( \my %conf, 'repository=s' )
    or die "Usage: $0 [ --repository <repository> ]";

my $depth = shift || 0;

init( $conf{repository} ) if !-e $conf{repository};
set_git_repo($conf{repository});

sub cayley {
    my ( $branch, $n, $root ) = @_;

    # create node
    return node($branch) if !$n;

    # branches
    my @nodes = (
        cayley( $branch, $n - 1 ),
        cayley( $branch, $n - 1 ),
        cayley( $branch, $n - 1 )
    );
    push @nodes, cayley( $branch, $n - 1 ) if $root;    # first item
    return node( $branch, @nodes);
}

cayley( "cayley-$depth", $depth, 1 );

