#!/bin/sh

repo=fractals
count="0 1 2 3 4 5 6"

# create cayley graphs
for i in $count ; do
    echo "# cayley $i"
    (
        echo 'digraph G { ranksep=3;'
        GIT_DIR=$repo/.git git log --pretty=format:"%h %p" --date-order cayley-$i \
        | perl -lna  -e 'print qq("$F[0]";), map {qq("$_"->"$F[0]";)} @F[ 1 .. $#F ]'
        echo '}'
    ) > cayley-$i.dot
    twopi -Tpng cayley-$i.dot > cayley-$i.png
done
    
# create sierpinski graphs
for i in $count ; do
    echo "# sierpinski $i"
    (
        echo 'digraph G {'
        GIT_DIR=$repo/.git git log --pretty=format:"%h %p" --date-order sierpinski-$i \
        | perl -lna  -e 'print qq("$F[0]";), map {qq("$_"->"$F[0]";)} @F[ 1 .. $#F ]'
        echo '}'
    ) > sierpinski-$i.dot
    dot -Tpng sierpinski-$i.dot > sierpinski-$i.png
done

